/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author FuryMercury
 */
public class Panel_Registros_Trabajadores extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Registros_Asistencia
     */
    public Panel_Registros_Trabajadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pBuscar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txfBuscar = new javax.swing.JTextField();
        spTabla = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pDatos = new javax.swing.JPanel();
        lblDNI = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblPrivilegio = new javax.swing.JLabel();
        lblSueldo = new javax.swing.JLabel();
        lblValidarPass = new javax.swing.JLabel();
        txfDNI = new javax.swing.JTextField();
        txfPassword = new javax.swing.JTextField();
        txfValidatePassword = new javax.swing.JTextField();
        txfNombre = new javax.swing.JTextField();
        txfApellidos = new javax.swing.JTextField();
        txfSueldo = new javax.swing.JTextField();
        cbPrivilegio = new javax.swing.JComboBox<>();
        pCRUD = new javax.swing.JPanel();
        btnTrabajadoresAgregar = new javax.swing.JButton();
        btnTrabajadoresActualizar = new javax.swing.JButton();
        btnTrabajadoresEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(250, 250, 250));
        setMaximumSize(new java.awt.Dimension(140, 20));
        setMinimumSize(new java.awt.Dimension(140, 20));
        setPreferredSize(new java.awt.Dimension(140, 20));
        setLayout(new java.awt.GridBagLayout());

        pBuscar.setBackground(new java.awt.Color(250, 250, 250));
        pBuscar.setMaximumSize(new java.awt.Dimension(400, 40));
        pBuscar.setMinimumSize(new java.awt.Dimension(400, 40));
        pBuscar.setName(""); // NOI18N
        pBuscar.setPreferredSize(new java.awt.Dimension(400, 40));
        pBuscar.setLayout(new java.awt.GridBagLayout());

        btnBuscar.setText("Buscar");
        btnBuscar.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pBuscar.add(btnBuscar, gridBagConstraints);

        txfBuscar.setMaximumSize(new java.awt.Dimension(200, 20));
        txfBuscar.setMinimumSize(new java.awt.Dimension(200, 20));
        txfBuscar.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pBuscar.add(txfBuscar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(pBuscar, gridBagConstraints);

        spTabla.setBackground(new java.awt.Color(250, 250, 250));
        spTabla.setMaximumSize(new java.awt.Dimension(600, 50));
        spTabla.setMinimumSize(new java.awt.Dimension(600, 50));
        spTabla.setPreferredSize(new java.awt.Dimension(600, 50));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setFocusable(false);
        jTable2.setMaximumSize(new java.awt.Dimension(400, 50));
        jTable2.setMinimumSize(new java.awt.Dimension(400, 50));
        jTable2.setPreferredSize(new java.awt.Dimension(400, 50));
        spTabla.setViewportView(jTable2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(spTabla, gridBagConstraints);

        pDatos.setBackground(new java.awt.Color(250, 250, 250));
        pDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)), "Datos Trabajadores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(60, 60, 60))); // NOI18N
        pDatos.setLayout(new java.awt.GridBagLayout());

        lblDNI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(60, 60, 60));
        lblDNI.setText("DNI :");
        lblDNI.setMaximumSize(new java.awt.Dimension(150, 20));
        lblDNI.setMinimumSize(new java.awt.Dimension(150, 20));
        lblDNI.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblDNI, gridBagConstraints);

        lblPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPass.setForeground(new java.awt.Color(60, 60, 60));
        lblPass.setText("Contraseña :");
        lblPass.setMaximumSize(new java.awt.Dimension(150, 20));
        lblPass.setMinimumSize(new java.awt.Dimension(150, 20));
        lblPass.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblPass, gridBagConstraints);

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(60, 60, 60));
        lblNombre.setText("Nombre :");
        lblNombre.setMaximumSize(new java.awt.Dimension(150, 20));
        lblNombre.setMinimumSize(new java.awt.Dimension(150, 20));
        lblNombre.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblNombre, gridBagConstraints);

        lblApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(60, 60, 60));
        lblApellidos.setText("Apellidos :");
        lblApellidos.setMaximumSize(new java.awt.Dimension(150, 20));
        lblApellidos.setMinimumSize(new java.awt.Dimension(150, 20));
        lblApellidos.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblApellidos, gridBagConstraints);

        lblPrivilegio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrivilegio.setForeground(new java.awt.Color(60, 60, 60));
        lblPrivilegio.setText("Privilegio :");
        lblPrivilegio.setMaximumSize(new java.awt.Dimension(150, 20));
        lblPrivilegio.setMinimumSize(new java.awt.Dimension(150, 20));
        lblPrivilegio.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblPrivilegio, gridBagConstraints);

        lblSueldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSueldo.setForeground(new java.awt.Color(60, 60, 60));
        lblSueldo.setText("Sueldo :");
        lblSueldo.setMaximumSize(new java.awt.Dimension(150, 20));
        lblSueldo.setMinimumSize(new java.awt.Dimension(150, 20));
        lblSueldo.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblSueldo, gridBagConstraints);

        lblValidarPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValidarPass.setForeground(new java.awt.Color(60, 60, 60));
        lblValidarPass.setText("Validar Contraseña :");
        lblValidarPass.setMaximumSize(new java.awt.Dimension(150, 20));
        lblValidarPass.setMinimumSize(new java.awt.Dimension(150, 20));
        lblValidarPass.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblValidarPass, gridBagConstraints);

        txfDNI.setMaximumSize(new java.awt.Dimension(250, 20));
        txfDNI.setMinimumSize(new java.awt.Dimension(250, 20));
        txfDNI.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(txfDNI, gridBagConstraints);

        txfPassword.setMaximumSize(new java.awt.Dimension(250, 20));
        txfPassword.setMinimumSize(new java.awt.Dimension(250, 20));
        txfPassword.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(txfPassword, gridBagConstraints);

        txfValidatePassword.setMaximumSize(new java.awt.Dimension(250, 20));
        txfValidatePassword.setMinimumSize(new java.awt.Dimension(250, 20));
        txfValidatePassword.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(txfValidatePassword, gridBagConstraints);

        txfNombre.setMaximumSize(new java.awt.Dimension(250, 20));
        txfNombre.setMinimumSize(new java.awt.Dimension(250, 20));
        txfNombre.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(txfNombre, gridBagConstraints);

        txfApellidos.setMaximumSize(new java.awt.Dimension(250, 20));
        txfApellidos.setMinimumSize(new java.awt.Dimension(250, 20));
        txfApellidos.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(txfApellidos, gridBagConstraints);

        txfSueldo.setMaximumSize(new java.awt.Dimension(250, 20));
        txfSueldo.setMinimumSize(new java.awt.Dimension(250, 20));
        txfSueldo.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(txfSueldo, gridBagConstraints);

        cbPrivilegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Trabajador" }));
        cbPrivilegio.setMaximumSize(new java.awt.Dimension(250, 20));
        cbPrivilegio.setMinimumSize(new java.awt.Dimension(250, 20));
        cbPrivilegio.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(cbPrivilegio, gridBagConstraints);

        pCRUD.setBackground(new java.awt.Color(250, 250, 250));
        pCRUD.setLayout(new java.awt.GridBagLayout());

        btnTrabajadoresAgregar.setText("AGREGAR");
        btnTrabajadoresAgregar.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pCRUD.add(btnTrabajadoresAgregar, gridBagConstraints);

        btnTrabajadoresActualizar.setText("ACTUALIZAR");
        btnTrabajadoresActualizar.setEnabled(false);
        btnTrabajadoresActualizar.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pCRUD.add(btnTrabajadoresActualizar, gridBagConstraints);

        btnTrabajadoresEliminar.setText("ELIMINAR");
        btnTrabajadoresEliminar.setEnabled(false);
        btnTrabajadoresEliminar.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pCRUD.add(btnTrabajadoresEliminar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(pCRUD, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(jSeparator1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(jSeparator7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(jSeparator8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(jSeparator9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(pDatos, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnTrabajadoresActualizar;
    public javax.swing.JButton btnTrabajadoresAgregar;
    public javax.swing.JButton btnTrabajadoresEliminar;
    public javax.swing.JComboBox<String> cbPrivilegio;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTable jTable2;
    public javax.swing.JLabel lblApellidos;
    public javax.swing.JLabel lblDNI;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblPass;
    public javax.swing.JLabel lblPrivilegio;
    public javax.swing.JLabel lblSueldo;
    public javax.swing.JLabel lblValidarPass;
    public javax.swing.JPanel pBuscar;
    public javax.swing.JPanel pCRUD;
    public javax.swing.JPanel pDatos;
    public javax.swing.JScrollPane spTabla;
    public javax.swing.JTextField txfApellidos;
    private javax.swing.JTextField txfBuscar;
    public javax.swing.JTextField txfDNI;
    public javax.swing.JTextField txfNombre;
    public javax.swing.JTextField txfPassword;
    public javax.swing.JTextField txfSueldo;
    public javax.swing.JTextField txfValidatePassword;
    // End of variables declaration//GEN-END:variables
}
