/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author FuryMercury
 */
public class Panel_Registro_Trabjadores_Agregar extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Registro_Trabjadores_Agregar
     */
    public Panel_Registro_Trabjadores_Agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pDatos = new javax.swing.JPanel();
        lblDNI = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblPrivilegio = new javax.swing.JLabel();
        lblSueldo = new javax.swing.JLabel();
        lblValidarPass = new javax.swing.JLabel();
        txfDNI = new javax.swing.JTextField();
        txfPassword = new javax.swing.JTextField();
        txfValidatePassword = new javax.swing.JTextField();
        txfNombre = new javax.swing.JTextField();
        txfApellidos = new javax.swing.JTextField();
        txfSueldo = new javax.swing.JTextField();
        cbPrivilegio = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        pDatos.setBackground(new java.awt.Color(250, 250, 250));
        pDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)), "Datos Trabajadores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(60, 60, 60))); // NOI18N
        pDatos.setMaximumSize(new java.awt.Dimension(600, 500));
        pDatos.setMinimumSize(new java.awt.Dimension(600, 500));
        pDatos.setPreferredSize(new java.awt.Dimension(600, 500));
        pDatos.setLayout(new java.awt.GridBagLayout());

        lblDNI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(60, 60, 60));
        lblDNI.setText("DNI :");
        lblDNI.setMaximumSize(new java.awt.Dimension(200, 20));
        lblDNI.setMinimumSize(new java.awt.Dimension(200, 20));
        lblDNI.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblDNI, gridBagConstraints);

        lblPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPass.setForeground(new java.awt.Color(60, 60, 60));
        lblPass.setText("Contraseña :");
        lblPass.setMaximumSize(new java.awt.Dimension(200, 20));
        lblPass.setMinimumSize(new java.awt.Dimension(200, 20));
        lblPass.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblPass, gridBagConstraints);

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(60, 60, 60));
        lblNombre.setText("Nombre :");
        lblNombre.setMaximumSize(new java.awt.Dimension(200, 20));
        lblNombre.setMinimumSize(new java.awt.Dimension(200, 20));
        lblNombre.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblNombre, gridBagConstraints);

        lblApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(60, 60, 60));
        lblApellidos.setText("Apellidos :");
        lblApellidos.setMaximumSize(new java.awt.Dimension(200, 20));
        lblApellidos.setMinimumSize(new java.awt.Dimension(200, 20));
        lblApellidos.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblApellidos, gridBagConstraints);

        lblPrivilegio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrivilegio.setForeground(new java.awt.Color(60, 60, 60));
        lblPrivilegio.setText("Privilegio :");
        lblPrivilegio.setMaximumSize(new java.awt.Dimension(200, 20));
        lblPrivilegio.setMinimumSize(new java.awt.Dimension(200, 20));
        lblPrivilegio.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblPrivilegio, gridBagConstraints);

        lblSueldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSueldo.setForeground(new java.awt.Color(60, 60, 60));
        lblSueldo.setText("Sueldo :");
        lblSueldo.setMaximumSize(new java.awt.Dimension(200, 20));
        lblSueldo.setMinimumSize(new java.awt.Dimension(200, 20));
        lblSueldo.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblSueldo, gridBagConstraints);

        lblValidarPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValidarPass.setForeground(new java.awt.Color(60, 60, 60));
        lblValidarPass.setText("Validar Contraseña :");
        lblValidarPass.setMaximumSize(new java.awt.Dimension(200, 20));
        lblValidarPass.setMinimumSize(new java.awt.Dimension(200, 20));
        lblValidarPass.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblValidarPass, gridBagConstraints);

        txfDNI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfDNI.setForeground(new java.awt.Color(60, 60, 60));
        txfDNI.setMaximumSize(new java.awt.Dimension(250, 25));
        txfDNI.setMinimumSize(new java.awt.Dimension(250, 25));
        txfDNI.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(txfDNI, gridBagConstraints);

        txfPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfPassword.setForeground(new java.awt.Color(60, 60, 60));
        txfPassword.setMaximumSize(new java.awt.Dimension(250, 25));
        txfPassword.setMinimumSize(new java.awt.Dimension(250, 25));
        txfPassword.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(txfPassword, gridBagConstraints);

        txfValidatePassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfValidatePassword.setForeground(new java.awt.Color(60, 60, 60));
        txfValidatePassword.setMaximumSize(new java.awt.Dimension(250, 25));
        txfValidatePassword.setMinimumSize(new java.awt.Dimension(250, 25));
        txfValidatePassword.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(txfValidatePassword, gridBagConstraints);

        txfNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfNombre.setForeground(new java.awt.Color(60, 60, 60));
        txfNombre.setMaximumSize(new java.awt.Dimension(250, 25));
        txfNombre.setMinimumSize(new java.awt.Dimension(250, 25));
        txfNombre.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(txfNombre, gridBagConstraints);

        txfApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfApellidos.setForeground(new java.awt.Color(60, 60, 60));
        txfApellidos.setMaximumSize(new java.awt.Dimension(250, 25));
        txfApellidos.setMinimumSize(new java.awt.Dimension(250, 25));
        txfApellidos.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(txfApellidos, gridBagConstraints);

        txfSueldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfSueldo.setForeground(new java.awt.Color(60, 60, 60));
        txfSueldo.setMaximumSize(new java.awt.Dimension(250, 25));
        txfSueldo.setMinimumSize(new java.awt.Dimension(250, 25));
        txfSueldo.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(txfSueldo, gridBagConstraints);

        cbPrivilegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Trabajador" }));
        cbPrivilegio.setMaximumSize(new java.awt.Dimension(250, 20));
        cbPrivilegio.setMinimumSize(new java.awt.Dimension(250, 20));
        cbPrivilegio.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(cbPrivilegio, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(jSeparator1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(jSeparator7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(jSeparator8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(jSeparator9, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cbPrivilegio;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JLabel lblApellidos;
    public javax.swing.JLabel lblDNI;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblPass;
    public javax.swing.JLabel lblPrivilegio;
    public javax.swing.JLabel lblSueldo;
    public javax.swing.JLabel lblValidarPass;
    public javax.swing.JPanel pDatos;
    public javax.swing.JTextField txfApellidos;
    public javax.swing.JTextField txfDNI;
    public javax.swing.JTextField txfNombre;
    public javax.swing.JTextField txfPassword;
    public javax.swing.JTextField txfSueldo;
    public javax.swing.JTextField txfValidatePassword;
    // End of variables declaration//GEN-END:variables
}
