/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author FuryMercury
 */
public class Panel_Registro_Trabajadores_Agregar extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Registro_Trabjadores_Agregar
     */
    public Panel_Registro_Trabajadores_Agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pDatos = new javax.swing.JPanel();
        lblDNI = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblPrivilegio = new javax.swing.JLabel();
        lblSueldo = new javax.swing.JLabel();
        cbPrivilegio = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        pCNombre1 = new javax.swing.JPanel();
        txfCNombre1 = new custom.CustomTextField();
        pCNombre2 = new javax.swing.JPanel();
        txfCNombre2 = new custom.CustomTextField();
        pCNombre3 = new javax.swing.JPanel();
        txfCNombre3 = new custom.CustomTextField();
        pCNombre4 = new javax.swing.JPanel();
        txfCNombre4 = new custom.CustomTextField();
        pCNombre5 = new javax.swing.JPanel();
        txfCNombre5 = new custom.CustomTextField();

        setLayout(new java.awt.GridBagLayout());

        pDatos.setBackground(new java.awt.Color(250, 250, 250));
        pDatos.setLayout(new java.awt.GridBagLayout());

        lblDNI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(60, 60, 60));
        lblDNI.setText("DNI :");
        lblDNI.setMaximumSize(new java.awt.Dimension(200, 35));
        lblDNI.setMinimumSize(new java.awt.Dimension(200, 35));
        lblDNI.setPreferredSize(new java.awt.Dimension(200, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblDNI, gridBagConstraints);

        lblPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPass.setForeground(new java.awt.Color(60, 60, 60));
        lblPass.setText("Contraseña :");
        lblPass.setMaximumSize(new java.awt.Dimension(200, 35));
        lblPass.setMinimumSize(new java.awt.Dimension(200, 35));
        lblPass.setPreferredSize(new java.awt.Dimension(200, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblPass, gridBagConstraints);

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(60, 60, 60));
        lblNombre.setText("Nombres :");
        lblNombre.setMaximumSize(new java.awt.Dimension(200, 35));
        lblNombre.setMinimumSize(new java.awt.Dimension(200, 35));
        lblNombre.setPreferredSize(new java.awt.Dimension(200, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblNombre, gridBagConstraints);

        lblApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(60, 60, 60));
        lblApellidos.setText("Apellidos :");
        lblApellidos.setMaximumSize(new java.awt.Dimension(200, 35));
        lblApellidos.setMinimumSize(new java.awt.Dimension(200, 35));
        lblApellidos.setPreferredSize(new java.awt.Dimension(200, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblApellidos, gridBagConstraints);

        lblPrivilegio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrivilegio.setForeground(new java.awt.Color(60, 60, 60));
        lblPrivilegio.setText("Privilegio :");
        lblPrivilegio.setMaximumSize(new java.awt.Dimension(200, 35));
        lblPrivilegio.setMinimumSize(new java.awt.Dimension(200, 35));
        lblPrivilegio.setPreferredSize(new java.awt.Dimension(200, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblPrivilegio, gridBagConstraints);

        lblSueldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSueldo.setForeground(new java.awt.Color(60, 60, 60));
        lblSueldo.setText("Sueldo :");
        lblSueldo.setMaximumSize(new java.awt.Dimension(200, 35));
        lblSueldo.setMinimumSize(new java.awt.Dimension(200, 35));
        lblSueldo.setPreferredSize(new java.awt.Dimension(200, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(lblSueldo, gridBagConstraints);

        cbPrivilegio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPrivilegio.setForeground(new java.awt.Color(60, 60, 60));
        cbPrivilegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "TRABAJADOR" }));
        cbPrivilegio.setFocusable(false);
        cbPrivilegio.setMaximumSize(new java.awt.Dimension(250, 30));
        cbPrivilegio.setMinimumSize(new java.awt.Dimension(250, 30));
        cbPrivilegio.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(cbPrivilegio, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(jSeparator1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(jSeparator7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(jSeparator8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(jSeparator9, gridBagConstraints);

        pCNombre1.setBackground(new java.awt.Color(255, 255, 255));
        pCNombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        pCNombre1.setMaximumSize(new java.awt.Dimension(100, 30));
        pCNombre1.setMinimumSize(new java.awt.Dimension(100, 30));
        pCNombre1.setPreferredSize(new java.awt.Dimension(100, 30));
        pCNombre1.setLayout(new java.awt.GridBagLayout());

        txfCNombre1.setBorder(null);
        txfCNombre1.setCaretColor(new java.awt.Color(60, 60, 60));
        txfCNombre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfCNombre1.setMaximumSize(new java.awt.Dimension(200, 28));
        txfCNombre1.setMinimumSize(new java.awt.Dimension(200, 28));
        txfCNombre1.setPhColor(new java.awt.Color(60, 60, 60));
        txfCNombre1.setPlaceholder("Ingresar DNI");
        txfCNombre1.setPreferredSize(new java.awt.Dimension(200, 28));
        txfCNombre1.setSelectionColor(new java.awt.Color(60, 60, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pCNombre1.add(txfCNombre1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(pCNombre1, gridBagConstraints);

        pCNombre2.setBackground(new java.awt.Color(255, 255, 255));
        pCNombre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        pCNombre2.setMaximumSize(new java.awt.Dimension(100, 30));
        pCNombre2.setMinimumSize(new java.awt.Dimension(100, 30));
        pCNombre2.setPreferredSize(new java.awt.Dimension(100, 30));
        pCNombre2.setLayout(new java.awt.GridBagLayout());

        txfCNombre2.setBorder(null);
        txfCNombre2.setCaretColor(new java.awt.Color(60, 60, 60));
        txfCNombre2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfCNombre2.setMaximumSize(new java.awt.Dimension(200, 28));
        txfCNombre2.setMinimumSize(new java.awt.Dimension(200, 28));
        txfCNombre2.setPhColor(new java.awt.Color(60, 60, 60));
        txfCNombre2.setPlaceholder("Ingresar contraseña");
        txfCNombre2.setPreferredSize(new java.awt.Dimension(200, 28));
        txfCNombre2.setSelectionColor(new java.awt.Color(60, 60, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pCNombre2.add(txfCNombre2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(pCNombre2, gridBagConstraints);

        pCNombre3.setBackground(new java.awt.Color(255, 255, 255));
        pCNombre3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        pCNombre3.setMaximumSize(new java.awt.Dimension(100, 30));
        pCNombre3.setMinimumSize(new java.awt.Dimension(100, 30));
        pCNombre3.setPreferredSize(new java.awt.Dimension(100, 30));
        pCNombre3.setLayout(new java.awt.GridBagLayout());

        txfCNombre3.setBorder(null);
        txfCNombre3.setCaretColor(new java.awt.Color(60, 60, 60));
        txfCNombre3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfCNombre3.setMaximumSize(new java.awt.Dimension(200, 28));
        txfCNombre3.setMinimumSize(new java.awt.Dimension(200, 28));
        txfCNombre3.setPhColor(new java.awt.Color(60, 60, 60));
        txfCNombre3.setPlaceholder("Ingresar Nombres");
        txfCNombre3.setPreferredSize(new java.awt.Dimension(200, 28));
        txfCNombre3.setSelectionColor(new java.awt.Color(60, 60, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pCNombre3.add(txfCNombre3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(pCNombre3, gridBagConstraints);

        pCNombre4.setBackground(new java.awt.Color(255, 255, 255));
        pCNombre4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        pCNombre4.setMaximumSize(new java.awt.Dimension(100, 30));
        pCNombre4.setMinimumSize(new java.awt.Dimension(100, 30));
        pCNombre4.setPreferredSize(new java.awt.Dimension(100, 30));
        pCNombre4.setLayout(new java.awt.GridBagLayout());

        txfCNombre4.setBorder(null);
        txfCNombre4.setCaretColor(new java.awt.Color(60, 60, 60));
        txfCNombre4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfCNombre4.setMaximumSize(new java.awt.Dimension(200, 28));
        txfCNombre4.setMinimumSize(new java.awt.Dimension(200, 28));
        txfCNombre4.setPhColor(new java.awt.Color(60, 60, 60));
        txfCNombre4.setPlaceholder("Ingresar Apellidos");
        txfCNombre4.setPreferredSize(new java.awt.Dimension(200, 28));
        txfCNombre4.setSelectionColor(new java.awt.Color(60, 60, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pCNombre4.add(txfCNombre4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(pCNombre4, gridBagConstraints);

        pCNombre5.setBackground(new java.awt.Color(255, 255, 255));
        pCNombre5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        pCNombre5.setMaximumSize(new java.awt.Dimension(100, 30));
        pCNombre5.setMinimumSize(new java.awt.Dimension(100, 30));
        pCNombre5.setPreferredSize(new java.awt.Dimension(100, 30));
        pCNombre5.setLayout(new java.awt.GridBagLayout());

        txfCNombre5.setBorder(null);
        txfCNombre5.setCaretColor(new java.awt.Color(60, 60, 60));
        txfCNombre5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txfCNombre5.setMaximumSize(new java.awt.Dimension(200, 28));
        txfCNombre5.setMinimumSize(new java.awt.Dimension(200, 28));
        txfCNombre5.setPhColor(new java.awt.Color(60, 60, 60));
        txfCNombre5.setPlaceholder("Ingresar Sueldo");
        txfCNombre5.setPreferredSize(new java.awt.Dimension(200, 28));
        txfCNombre5.setSelectionColor(new java.awt.Color(60, 60, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pCNombre5.add(txfCNombre5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pDatos.add(pCNombre5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(pDatos, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cbPrivilegio;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JLabel lblApellidos;
    public javax.swing.JLabel lblDNI;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblPass;
    public javax.swing.JLabel lblPrivilegio;
    public javax.swing.JLabel lblSueldo;
    private javax.swing.JPanel pCNombre1;
    private javax.swing.JPanel pCNombre2;
    private javax.swing.JPanel pCNombre3;
    private javax.swing.JPanel pCNombre4;
    private javax.swing.JPanel pCNombre5;
    public javax.swing.JPanel pDatos;
    public custom.CustomTextField txfCNombre1;
    public custom.CustomTextField txfCNombre2;
    public custom.CustomTextField txfCNombre3;
    public custom.CustomTextField txfCNombre4;
    public custom.CustomTextField txfCNombre5;
    // End of variables declaration//GEN-END:variables
}
